stories/ChangeLog.stories.mdx
Adds a changelog to the storybook so we can see component's current state.
It's based on @rhannandrade work done on https://github.com/labcodes/labstorybook/pull/12.
=> New changelog

.circleci/config.yml, .gitignore, labsystem/package-lock.json, package-lock.json
Setup CircleCI for labstorybook project.
Check if you see any anomalies or if something is missing.
=> Setup CircleCI for the project

README.md, labsystem/samples/SampleComponent.js, labsystem/samples/SampleComponent.stories.mdx
**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-121
- Check if there is a `samples` directory with templates for creating a new component;
- Check if there are instructions on `README.md` file on how to use the samples.
**Description of your solution:**
This PR introduces samples for creating new components. Instructions on how to use it are included on `README.md` file.
=> DSYS-121/sample-component

labsystem/scss/components/_lab-alerts.scss
**Link to task:**
https://labcodes.atlassian.net/browse/DSYS-18 (QA 09/11)
- With the LabSystem running, go to the "Component/System Messages" div in the LabStoryBook, then check if everything is rendered as expected.
- Locally, from labstorybook dir, run `npm test`, then check if all tests are passing.
This PR fixes the CSS of `Alerts` according to _QA from 04/11/2020_.
=> DSYS-18/alerts-qa

labsystem/samples/SampleComponent.stories.mdx
We have very different docs for our components, so the aim of this PR is to create a pattern to be followed.
Note that some indentation may be odd, but the stories behave really weirdly with the previews and need a very delicate setting to render properly that I can't quite understand.
=> Storybook template

stories/ChangeLog.stories.mdx
Jira issue: [https://labcodes.atlassian.net/browse/DSYS-170](https://labcodes.atlassian.net/browse/DSYS-170)
This PR updates the components' status of our Confetti Design System using our Tags. I also added the release version to each component.
=> Update changelog 

labsystem/scss/components/_lab-card.scss, labsystem/scss/variables/_themes.scss, labsystem/src/Card/CardDivider.js, labsystem/src/Card/CardDivider.test.js, labsystem/src/Card/CardHeader.js, labsystem/src/Card/CardHeader.test.js, labsystem/src/Card/CardImage.test.js, labsystem/src/Card/DoubleAction.js, labsystem/src/Card/DoubleAction.test.js, labsystem/src/Card/FilledCard.js, labsystem/src/Card/FilledCard.test.js, labsystem/src/Card/LinkAction.test.js, labsystem/src/Card/OutlineCard.js, labsystem/src/Card/OutlineCard.test.js, labsystem/src/Card/OutlineFilledCard.js, labsystem/src/Card/OutlineFilledCard.test.js, labsystem/src/Card/__snapshots__/CardDivider.test.js.snap, labsystem/src/Card/__snapshots__/CardHeader.test.js.snap, labsystem/src/Card/__snapshots__/CardImage.test.js.snap, labsystem/src/Card/__snapshots__/DoubleAction.test.js.snap, labsystem/src/Card/__snapshots__/FilledCard.test.js.snap, labsystem/src/Card/__snapshots__/LinkAction.test.js.snap, labsystem/src/Card/__snapshots__/OutlineCard.test.js.snap, labsystem/src/Card/__snapshots__/OutlineFilledCard.test.js.snap, labsystem/src/Card/contexts.js, playgrounds/CardPlayground.js, playgrounds/scss/playgrounds.scss
**Link to task:** https://labcodes.atlassian.net/browse/DSYS-26
**Link to staging app:** https://card-ui--labstorybook-master.netlify.app/
**Details:**
This PR contains all the UI, playground and tests for the Cards.
Please, check all the aspects of the Cards UI on staging :]
=> DSYS-26: Cards UI + Tests

stories/Accessibility.stories.mdx, stories/ChangeLog.stories.mdx
**Link to issue:** https://labcodes.atlassian.net/browse/DSYS-139
**Link to staging app:** https://docs-accessibility--labstorybook-master.netlify.app/?path=/docs/getting-started-accessibility--page
Added an accessibility section in Getting Started with an overview about what accessibility means for the Design System and which methods we are using for testing.
Also updated the [changelog](https://docs-accessibility--labstorybook-master.netlify.app/?path=/docs/getting-started-changelog--page) with an accessibility column and proposed a new convention for the status with descriptions.
=> Accessibility Statement

.storybook/scss/doc-search.scss, labsystem/scss/components/_lab-icon.scss, labsystem/src/Alert.test.js, labsystem/src/Buttons/OutlineButton.test.js, labsystem/src/Buttons/__snapshots__/OutlineButton.test.js.snap, labsystem/src/Icon.js, labsystem/src/Search/AbstractSearch.js, labsystem/src/Search/StandardSearch.test.js, labsystem/src/Search/__snapshots__/AbstractSearch.test.js.snap, labsystem/src/Search/__snapshots__/InlineSearch.test.js.snap, labsystem/src/Search/__snapshots__/StandardSearch.test.js.snap, labsystem/src/Tags/SimpleTag.test.js, labsystem/src/Tags/__snapshots__/SimpleTag.test.js.snap, labsystem/src/__snapshots__/Alert.test.js.snap, playgrounds/TextInputPlayground.js, playgrounds/assets.js, stories/IconAndBadge.stories.mdx
https://labcodes.atlassian.net/browse/DSYS-164
This PR replaces occurrences of `lupe` with `magnifying-glass` overall. Snapshots are updated accordingly.
Run: `npm test` from the `labsystem` folder for testing.
=> DSYS-164: Icon

labsystem/.npmignore, labsystem/package-lock.json, labsystem/package.json
**Link to task:** https://labcodes.atlassian.net/browse/DSYS-173
**Description:**
This task adds a prepack script to our DS package, so that the src folder files are transpiled.
I tested it on our boierplate to be sure no more imcompatibilities happen.
For this to be possible, I needed to add a .npmignore file, so the task related to that was fixed here as well. :]
=> DSYS-173: Transpile files

labsystem/samples/SampleComponent.stories.mdx, playgrounds/CheckboxPlayground.js, playgrounds/RadioPlayground.js, playgrounds/SystemMessagesPlayground.js, playgrounds/TagPlayground.js, playgrounds/TextInputPlayground.js, playgrounds/scss/playgrounds.scss, stories/Checkbox.stories.mdx, stories/Radio.stories.mdx, stories/SystemMessages.stories.mdx, stories/Tag.stories.mdx, stories/TextInput.stories.mdx
**Jira issue:** https://labcodes.atlassian.net/browse/DSYS-141
**Staging:** https://playground-ui--labstorybook-master.netlify.app/
**Details**
We have a custom playground, but it looks different in every page. Its styles are also not the best they could be, with several input types, mixing our inputs with default ones, and using suboptimal choices on others. Here I create a pattern to follow with a simple UI, and make use of components based on our own guidelines.
=> UI Adjustments

labsystem/src/Toggle.js, labsystem/src/Toggle.test.js, labsystem/src/__snapshots__/Toggle.test.js.snap, stories/Toggle.stories.mdx
**Jira:** https://labcodes.atlassian.net/browse/DSYS-158
**Staging:** https://fix-toggle--labstorybook-master.netlify.app/?path=/docs/components-toggle--sample-toggle#toggle-themes
**Details**
* Renamed `theme` pro for `color` to be consistent with other components.
* All tests have passed
=> Fix toggle

.storybook/config.js, .storybook/main.js, .storybook/presets.js, .storybook/preview.js, stories/Buttons.stories.mdx, stories/ChangeLog.stories.mdx, stories/Checkbox.stories.mdx, stories/Colors.stories.mdx, stories/IconAndBadge.stories.mdx, stories/Links.stories.mdx, stories/Motions.stories.mdx, stories/NarrowSidebar.stories.mdx, stories/Principles.stories.mdx, stories/Radio.stories.mdx, stories/Search.stories.mdx, stories/Spacing.stories.mdx, stories/SystemMessages.stories.mdx, stories/Tag.stories.mdx, stories/TextInput.stories.mdx, stories/Toggle.stories.mdx, stories/Tooltip.stories.mdx, stories/Typography.stories.mdx
**Jira Issue:** https://labcodes.atlassian.net/browse/DSYS-140
This PR fixes storybook's configuration (Done by @lucianoratamero ) and orders our stories. It now looks like the image below.
=> Organize sidebar navigation

stories/Tooltip.stories.mdx
**Jira issue:** https://labcodes.atlassian.net/browse/DSYS-159
**Staging:** https://fix-tooltip--labstorybook-master.netlify.app/?path=/docs/components-tooltip--placement#placement
=> Update tooltip docs to fix typos and wrong label texts

stories/base/Responsiveness.stories.mdx
Fix typo found on QA of Grid story. https://labcodes.atlassian.net/browse/DSYS-134
=> Fix typo on responsiveness' story

labsystem/src/Card/CardDivider.js, labsystem/src/Card/CardHeader.js, labsystem/src/Card/CardImage.js, labsystem/src/Card/DoubleAction.js, labsystem/src/Card/FilledCard.js, labsystem/src/Card/LinkAction.js, labsystem/src/Card/OutlineCard.js, labsystem/src/Card/OutlineFilledCard.js, labsystem/src/Card/__snapshots__/CardHeader.test.js.snap
Issue: https://labcodes.atlassian.net/browse/DSYS-206
=> Card props description

labsystem/scss/base/_all.scss
**Link to task:** https://labcodes.atlassian.net/browse/DSYS-200
Since all components were implemented inside the storybook, and it already applied this css rule for all elements, no components were affected, so I think there's not even that much to validate @debscorreia .
=> DSYS-200: Add box-sizing: border-box; for all elements

labsystem/package-lock.json, labsystem/package.json, labsystem/scss/components/_lab-card.scss, labsystem/src/Button/Button.js, labsystem/src/Button/OutlineButton.js, labsystem/src/Button/TextButton.js, labsystem/src/Input/AbstractTextInput.js, labsystem/src/Input/__snapshots__/AbstractTextInput.test.js.snap, labsystem/src/Input/__snapshots__/EmailInput.test.js.snap, labsystem/src/Input/__snapshots__/PasswordInput.test.js.snap, labsystem/src/Input/__snapshots__/TextInput.test.js.snap, labsystem/src/Toggle.js, labsystem/src/Toggle.test.js, labsystem/src/__snapshots__/Toggle.test.js.snap, labsystem/src/index.js, stories/Toggle.stories.mdx, stories/base/Grid.stories.mdx
**Link to task:** https://labcodes.atlassian.net/browse/DSYS-208
**Staging app:** https://implementation-fixes--labstorybook-master.netlify.app/
These are fixes related to my experience when I was implementing the testing form page.
They mostly don't interfere with anything, and I need it to finish up the form, so please review it asap :]
=> Implementation fixes

labsystem/scss/base/_all.scss, labsystem/scss/base/_forms.scss, labsystem/scss/components/_lab-alerts.scss, labsystem/scss/components/_lab-dialog.scss, labsystem/src/Banner.js, labsystem/src/__snapshots__/Banner.test.js.snap
**Link to task:** https://labcodes.atlassian.net/browse/DSYS-214
**Staging app:** https://design-review-fixes--labstorybook-master.netlify.app/
This PR fixes z-index for banners and adds base styles for fieldsets and legends.
=> DSYS-214: Design review fixes

PULL_REQUEST_TEMPLATE.md, labsystem/.npmignore, labsystem/PULL_REQUEST_TEMPLATE.md, stories/getting-started/How to Contribute.stories.mdx
**Link to task:** https://labcodes.atlassian.net/browse/DSYS-215
**Staging app:** https://pr-template--labstorybook-master.netlify.app/
**How to test:** Try to open a PR, it should start with the text contained in the PR template
**Description of your solution:** Added two files that Github recognizes as templates for the PRs.
=> DSYS-215: Add PR templates for both packages

.storybook/scss/doc-base.scss, .storybook/scss/doc-narrow-sidebar.scss, .storybook/scss/doc-type.scss, .storybook/scss/doc-utils.scss, labsystem/scss/base/_titles.scss, labsystem/scss/components/_lab-alerts.scss, labsystem/scss/components/_lab-button.scss, labsystem/scss/components/_lab-card.scss, labsystem/scss/components/_lab-checkbox.scss, labsystem/scss/components/_lab-dialog.scss, labsystem/scss/components/_lab-inputs.scss, labsystem/scss/components/_lab-radio.scss, labsystem/scss/components/_lab-searchinput.scss, labsystem/scss/components/_lab-sidebar.scss, labsystem/scss/components/_lab-tag.scss, labsystem/scss/components/_lab-toggle.scss, labsystem/scss/components/_lab-tooltip.scss, labsystem/scss/variables/_borders.scss, labsystem/scss/variables/_spacing.scss, labsystem/scss/variables/_typography.scss, playgrounds/scss/playgrounds.scss, stories/Colors.stories.mdx, stories/Spacing.stories.mdx, stories/Typography.stories.mdx, stories/getting-started/SetupConfetti.stories.mdx
**Jira issue:** https://labcodes.atlassian.net/browse/DSYS-166
**Staging app:** https://fix-tokens--labstorybook-master.netlify.app/
=> Fix tokens

playgrounds/ButtonPlayground.js, playgrounds/CardPlayground.js, playgrounds/CheckboxPlayground.js, playgrounds/DialogPlayground.js, playgrounds/NarrowSidebarPlayground.js, playgrounds/RadioPlayground.js, playgrounds/SystemMessagesPlayground.js, playgrounds/TagPlayground.js, playgrounds/TextInputPlayground.js, playgrounds/scss/playgrounds.scss
**Link to task: https://labcodes.atlassian.net/browse/CSYS-191**
**Staging app:** https://playgrounds-improvements--labstorybook-master.netlify.app/
- Check if all Toggles in components playgrounds are wrapped with `<fieldset>` using `<legend>`
- Check if there are playgrounds still using `<br />` (they shouldn't)
- Check if controls perform as expected in all playgrounds
- Check if the layout crashes in any breakpoint for all playgrounds
**Description of your solution:**
- Added styles for `<h4>`, `<legend>`, `<label>`, and `<select>`
- Added a class to display controls inline 
- Organized code in stylesheet
- Updated `<fieldset>` use to alway have a `<legend>` assigned
- Wrapped all toggle controls with a `<fieldset>` and `<legend>`
- Updated some control types (input …
=> Playgrounds improvements

.storybook/scss/doc-dialog.scss, .storybook/scss/doc-utils.scss, stories/getting-started/How to Contribute.stories.mdx
**Link to task:** https://labcodes.atlassian.net/browse/CSYS-282
**Staging app:** https://npm-config--labstorybook-master.netlify.app/
- open the staging app;
- verify that the new documentation on how to contribute is satisfatory.
**Description of your solution:**
Added new docs and links about semver and npm publishing to `How to contribute` page.
=> CSYS-282: Npm config
